<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<Authors>true_mogician</Authors>
		<Description>Common utilities for true_mogician's mods</Description>
		<Version>1.0.0</Version>
		<Title>true_mogician's RimWorld Mod Utilities</Title>
		<RootNamespace>TrueMogician.RimWorld.Utility</RootNamespace>
		<GameDir>$(SolutionDir)RimWorld</GameDir>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<DebugType>embedded</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Tasks\*.cs" />
		<Compile Include="Tasks\*.cs" Condition="'$(DesignTimeBuild)' == 'true'" />
		<None Include="Tasks\*.cs" Condition="'$(DesignTimeBuild)' != 'true'" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.44.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4633" />
		<PackageReference Include="Lib.Harmony" Version="2.4.2" />
		<PackageReference Include="Microsoft.Build.Utilities.Core" Version="18.0.2">
			<PrivateAssets>all</PrivateAssets>
			<ExcludeAssets>runtime</ExcludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="5.0.0">
			<PrivateAssets>all</PrivateAssets>
			<ExcludeAssets>runtime</ExcludeAssets>
		</PackageReference>
		<PackageReference Include="TrueMogician.Extensions.Enumerable" Version="2.1.0" PrivateAssets="all" />
	</ItemGroup>
</Project>