<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<Authors>true_mogician</Authors>
		<PackageId>TrueMogician.ExactStorage.PUAH</PackageId>
		<Version>0.0.1</Version>
		<Title>Exact Storage for Pick Up And Haul</Title>
		<AssemblyTitle>$(Title)</AssemblyTitle>
		<RootNamespace>TrueMogician.RimWorld.ExactStorage.PUAH</RootNamespace>
	</PropertyGroup>

	<PropertyGroup>
		<ProjectRoot>$(ProjectDir)..\</ProjectRoot>
		<DistDir>$(ProjectRoot)Dist\</DistDir>
		<AssemblyDistDir>$(DistDir)PUAH\1.6\Assemblies\</AssemblyDistDir>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<DebugType>embedded</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectProperty Include="PackageId" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="5.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="ThisAssembly.AssemblyInfo" Version="2.1.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="ThisAssembly.Project" Version="2.1.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<ProjectReference Include="..\Source\ExactStorage.csproj" />
		<ProjectReference Include="$(UtilityProjectPath)" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="References\*.dll" />
		<Reference Include="IHoldMultipleThings" HintPath="References\IHoldMultipleThings.dll" Private="false" />
		<Reference Include="PickUpAndHaul" HintPath="References\PickUpAndHaul.dll" Private="false" />
	</ItemGroup>

	<Target Name="Distribute" AfterTargets="Build">
		<Copy SourceFiles="$(TargetPath)" DestinationFiles="$(AssemblyDistDir)$(AssemblyName).dll" />
		<Message Importance="High" Text="Distributed $(TargetPath) -&gt; $(AssemblyDistDir)" />
	</Target>

	<Target Name="CustomClean" AfterTargets="Clean">
		<ItemGroup>
			<DirsToDelete Include="$(DistDir)PUAH" />
		</ItemGroup>
		<RemoveDir Directories="@(DirsToDelete)" />
		<Message Text="Custom files and directories cleaned" Importance="High" />
	</Target>
</Project>